name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/markxnelson/docker-test:${GITHUB_RUN_NUMBER}
    - name: Push the Docker image
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: docker-test
